2020-04-24 08:57:31,118 ERROR 14904 [-/::1/-/17ms GET /login?name=cpic&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` = 'cpic' AND `password` = '123456' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` = 'cpic' AND `password` = '123456' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14904
hostname: DESKTOP-1JNFRSL

2020-04-24 09:08:02,489 ERROR 14904 [-/::1/-/5ms GET /login?name=cpic&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` = 'cpic' AND `password` = '123456' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` = 'cpic' AND `password` = '123456' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 14904
hostname: DESKTOP-1JNFRSL

2020-04-24 09:13:06,398 ERROR 12900 [-/::1/-/18ms GET /login?name=cpic&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` = 'cpic' AND `password` = '123456' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` = 'cpic' AND `password` = '123456' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 12900
hostname: DESKTOP-1JNFRSL

2020-04-24 14:57:09,364 ERROR 6408 [-/::1/-/53ms POST /register] nodejs.TypeError: ctx.service.login.register is not a function
    at RegisterController.register (C:\Users\zhang\Desktop\egg\app\controller\register.js:7:44)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 6408
hostname: DESKTOP-1JNFRSL

2020-04-24 15:03:12,277 ERROR 19624 [-/::1/-/11ms POST /register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'surePassword' in 'field list'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `password`, `surePassword`, `phone`, `nick`) VALUES('kanyu', '12345678', '12345678', '15072409088', 'nick')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'surePassword' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `user`(`name`, `password`, `surePassword`, `phone`, `nick`) VALUES('kanyu', '12345678', '12345678', '15072409088', 'nick')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 19624
hostname: DESKTOP-1JNFRSL

2020-04-24 15:07:38,169 ERROR 14208 [-/::1/-/65ms POST /register] nodejs.ER_WARN_DATA_OUT_OF_RANGEError: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'id' at row 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', NULL, '12345678', 1, 1587712058150)
code: "ER_WARN_DATA_OUT_OF_RANGE"
errno: 1264
sqlMessage: "Out of range value for column 'id' at row 1"
sqlState: "22003"
index: 0
sql: "INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', NULL, '12345678', 1, 1587712058150)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_WARN_DATA_OUT_OF_RANGEError"
pid: 14208
hostname: DESKTOP-1JNFRSL

2020-04-24 15:08:43,181 ERROR 16648 [-/::1/-/73ms POST /register] nodejs.ER_WARN_DATA_OUT_OF_RANGEError: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'id' at row 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', '2020-04-24 15:08:43.171', '12345678', 1, 1587712123171)
code: "ER_WARN_DATA_OUT_OF_RANGE"
errno: 1264
sqlMessage: "Out of range value for column 'id' at row 1"
sqlState: "22003"
index: 0
sql: "INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', '2020-04-24 15:08:43.171', '12345678', 1, 1587712123171)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_WARN_DATA_OUT_OF_RANGEError"
pid: 16648
hostname: DESKTOP-1JNFRSL

2020-04-24 15:12:23,729 ERROR 16648 [-/::1/-/10ms POST /register] nodejs.ER_WARN_DATA_OUT_OF_RANGEError: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'id' at row 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', '2020-04-24 15:12:23.726', '12345678', 1, 1587712343726)
code: "ER_WARN_DATA_OUT_OF_RANGE"
errno: 1264
sqlMessage: "Out of range value for column 'id' at row 1"
sqlState: "22003"
index: 0
sql: "INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', '2020-04-24 15:12:23.726', '12345678', 1, 1587712343726)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_WARN_DATA_OUT_OF_RANGEError"
pid: 16648
hostname: DESKTOP-1JNFRSL

2020-04-24 15:13:48,929 ERROR 16648 [-/::1/-/9ms POST /register] nodejs.ER_WARN_DATA_OUT_OF_RANGEError: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'id' at row 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', '2020-04-24 15:13:48.926', '12345678', 1, 1587712428926)
code: "ER_WARN_DATA_OUT_OF_RANGE"
errno: 1264
sqlMessage: "Out of range value for column 'id' at row 1"
sqlState: "22003"
index: 0
sql: "INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', '2020-04-24 15:13:48.926', '12345678', 1, 1587712428926)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_WARN_DATA_OUT_OF_RANGEError"
pid: 16648
hostname: DESKTOP-1JNFRSL

2020-04-24 15:14:31,275 ERROR 16648 [-/::1/-/6ms POST /register] nodejs.ER_WARN_DATA_OUT_OF_RANGEError: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'id' at row 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', '2020-04-24 15:14:31.272', '12345678', 1, 1587712471272)
code: "ER_WARN_DATA_OUT_OF_RANGE"
errno: 1264
sqlMessage: "Out of range value for column 'id' at row 1"
sqlState: "22003"
index: 0
sql: "INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', '2020-04-24 15:14:31.272', '12345678', 1, 1587712471272)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_WARN_DATA_OUT_OF_RANGEError"
pid: 16648
hostname: DESKTOP-1JNFRSL

2020-04-24 15:15:48,949 ERROR 688 [-/::1/-/61ms POST /register] nodejs.ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'syfhe4wg' for column 'id' at row 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', '2020-04-24 15:15:48.940', '12345678', '1', 'syfhe4wg')
code: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELD"
errno: 1366
sqlMessage: "Incorrect integer value: 'syfhe4wg' for column 'id' at row 1"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `user`(`name`, `nick`, `phone`, `regist_time`, `password`, `type`, `id`) VALUES('kanyu', 'nick', '15072409088', '2020-04-24 15:15:48.940', '12345678', '1', 'syfhe4wg')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError"
pid: 688
hostname: DESKTOP-1JNFRSL

2020-04-26 10:46:57,657 ERROR 8272 [-/::1/-/48ms POST /addOneTodo] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = false L' at line 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `todos` WHERE `params` = `user_id` = 'kv6iljoa', `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = false LIMIT 0, 1
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = false L' at line 1"
sqlState: "42000"
index: 0
sql: "SELECT * FROM `todos` WHERE `params` = `user_id` = 'kv6iljoa', `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = false LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 8272
hostname: DESKTOP-1JNFRSL

2020-04-26 10:49:23,773 ERROR 8272 [-/::1/-/3ms POST /addOneTodo] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = 0 LIMIT' at line 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `todos` WHERE `params` = `user_id` = 'kv6iljoa', `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = 0 LIMIT 0, 1
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = 0 LIMIT' at line 1"
sqlState: "42000"
index: 0
sql: "SELECT * FROM `todos` WHERE `params` = `user_id` = 'kv6iljoa', `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = 0 LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 8272
hostname: DESKTOP-1JNFRSL

2020-04-26 10:50:48,184 ERROR 8272 [-/::1/-/2ms POST /addOneTodo] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = '0' LIM' at line 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `todos` WHERE `params` = `user_id` = 'kv6iljoa', `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = '0' LIMIT 0, 1
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = '0' LIM' at line 1"
sqlState: "42000"
index: 0
sql: "SELECT * FROM `todos` WHERE `params` = `user_id` = 'kv6iljoa', `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = '0' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 8272
hostname: DESKTOP-1JNFRSL

2020-04-26 10:50:52,383 ERROR 8272 [-/::1/-/9ms POST /addOneTodo] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = '0' LIM' at line 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `todos` WHERE `params` = `user_id` = 'kv6iljoa', `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = '0' LIMIT 0, 1
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = '0' LIM' at line 1"
sqlState: "42000"
index: 0
sql: "SELECT * FROM `todos` WHERE `params` = `user_id` = 'kv6iljoa', `day` = '2020-04-26', `desc` = '中午饭去渔米情吃', `computed` = '0' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 8272
hostname: DESKTOP-1JNFRSL

2020-04-26 10:51:26,561 ERROR 8272 [-/::1/-/4ms POST /addOneTodo] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `day` = '2020-04-26', `desc` = '中午饭去渔米情吃' LIMIT 0, 1' at line 1
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `todos` WHERE `params` = `user_id` = 'kv6iljoa', `day` = '2020-04-26', `desc` = '中午饭去渔米情吃' LIMIT 0, 1
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `day` = '2020-04-26', `desc` = '中午饭去渔米情吃' LIMIT 0, 1' at line 1"
sqlState: "42000"
index: 0
sql: "SELECT * FROM `todos` WHERE `params` = `user_id` = 'kv6iljoa', `day` = '2020-04-26', `desc` = '中午饭去渔米情吃' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 8272
hostname: DESKTOP-1JNFRSL

2020-04-26 10:59:06,960 ERROR 7860 [-/::1/-/31ms GET /queryTodo?userId=kv6iljoa&day=2020-04-26] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'userId' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `todos` WHERE `userId` = 'kv6iljoa' AND `day` = '2020-04-26' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'userId' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `todos` WHERE `userId` = 'kv6iljoa' AND `day` = '2020-04-26' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 7860
hostname: DESKTOP-1JNFRSL

2020-04-26 15:32:38,134 ERROR 17532 [-/::1/-/4ms POST /switchStatus] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:50:10)
    at RDSClient.createPromise [as update] (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:30:15)
    at todoService.switchStatus (C:\Users\zhang\Desktop\egg\app\service\todo.js:40:41)
    at todoController.switchStatus (C:\Users\zhang\Desktop\egg\app\controller\todo.js:19:43)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17532
hostname: DESKTOP-1JNFRSL

2020-04-26 15:32:39,690 ERROR 17532 [-/::1/-/1ms POST /switchStatus] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:50:10)
    at RDSClient.createPromise [as update] (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:30:15)
    at todoService.switchStatus (C:\Users\zhang\Desktop\egg\app\service\todo.js:40:41)
    at todoController.switchStatus (C:\Users\zhang\Desktop\egg\app\controller\todo.js:19:43)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17532
hostname: DESKTOP-1JNFRSL

2020-04-26 15:32:40,059 ERROR 17532 [-/::1/-/2ms POST /switchStatus] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:50:10)
    at RDSClient.createPromise [as update] (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:30:15)
    at todoService.switchStatus (C:\Users\zhang\Desktop\egg\app\service\todo.js:40:41)
    at todoController.switchStatus (C:\Users\zhang\Desktop\egg\app\controller\todo.js:19:43)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17532
hostname: DESKTOP-1JNFRSL

2020-04-26 15:32:40,364 ERROR 17532 [-/::1/-/2ms POST /switchStatus] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:50:10)
    at RDSClient.createPromise [as update] (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:30:15)
    at todoService.switchStatus (C:\Users\zhang\Desktop\egg\app\service\todo.js:40:41)
    at todoController.switchStatus (C:\Users\zhang\Desktop\egg\app\controller\todo.js:19:43)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17532
hostname: DESKTOP-1JNFRSL

2020-04-26 15:32:40,601 ERROR 17532 [-/::1/-/1ms POST /switchStatus] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:50:10)
    at RDSClient.createPromise [as update] (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:30:15)
    at todoService.switchStatus (C:\Users\zhang\Desktop\egg\app\service\todo.js:40:41)
    at todoController.switchStatus (C:\Users\zhang\Desktop\egg\app\controller\todo.js:19:43)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17532
hostname: DESKTOP-1JNFRSL

2020-04-26 15:34:25,732 ERROR 17532 [-/::1/-/2ms POST /switchStatus] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:50:10)
    at RDSClient.createPromise [as update] (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:30:15)
    at todoService.switchStatus (C:\Users\zhang\Desktop\egg\app\service\todo.js:40:41)
    at todoController.switchStatus (C:\Users\zhang\Desktop\egg\app\controller\todo.js:19:43)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17532
hostname: DESKTOP-1JNFRSL

2020-04-26 15:34:25,988 ERROR 17532 [-/::1/-/1ms POST /switchStatus] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:50:10)
    at RDSClient.createPromise [as update] (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:30:15)
    at todoService.switchStatus (C:\Users\zhang\Desktop\egg\app\service\todo.js:40:41)
    at todoController.switchStatus (C:\Users\zhang\Desktop\egg\app\controller\todo.js:19:43)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17532
hostname: DESKTOP-1JNFRSL

2020-04-26 15:36:44,239 ERROR 17532 [-/::1/-/1ms POST /switchStatus] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:50:10)
    at RDSClient.createPromise [as update] (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:30:15)
    at todoService.switchStatus (C:\Users\zhang\Desktop\egg\app\service\todo.js:40:41)
    at todoController.switchStatus (C:\Users\zhang\Desktop\egg\app\controller\todo.js:19:43)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17532
hostname: DESKTOP-1JNFRSL

2020-04-26 15:39:38,678 ERROR 17532 [-/::1/-/1ms POST /switchStatus] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:50:10)
    at RDSClient.createPromise [as update] (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:30:15)
    at todoService.switchStatus (C:\Users\zhang\Desktop\egg\app\service\todo.js:40:41)
    at todoController.switchStatus (C:\Users\zhang\Desktop\egg\app\controller\todo.js:19:43)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17532
hostname: DESKTOP-1JNFRSL

